export const KIF_IMPORT_ERROR_CODES = Object.freeze({
  KIF_FILE_NOT_SELECTED: "KIF_FILE_NOT_SELECTED",
  KIF_FILE_EMPTY: "KIF_FILE_EMPTY",
  KIF_FILE_TOO_LARGE: "KIF_FILE_TOO_LARGE",
  KIF_FILE_EXTENSION_INVALID: "KIF_FILE_EXTENSION_INVALID",
  KIF_READ_FAILED: "KIF_READ_FAILED",
  KIF_ENCODING_UNSUPPORTED: "KIF_ENCODING_UNSUPPORTED",
  INVALID_KIF_FORMAT: "INVALID_KIF_FORMAT",
  KIF_HEADER_INVALID: "KIF_HEADER_INVALID",
  KIF_MOVES_NOT_FOUND: "KIF_MOVES_NOT_FOUND",
  KIF_MOVE_INVALID: "KIF_MOVE_INVALID",
  KIF_MOVE_NUMBER_DUPLICATE: "KIF_MOVE_NUMBER_DUPLICATE",
  KIF_MOVE_NUMBER_GAP: "KIF_MOVE_NUMBER_GAP",
  KIF_TERMINATION_INVALID: "KIF_TERMINATION_INVALID",
  KIF_CONTENT_CONFLICT: "KIF_CONTENT_CONFLICT",
  KIF_IMPORT_CANCELLED: "KIF_IMPORT_CANCELLED",
  KIF_PREVIEW_NOT_FOUND: "KIF_PREVIEW_NOT_FOUND"
});

export const KIF_IMPORT_WARNING_CODES = Object.freeze({
  HEADER_MISSING: "HEADER_MISSING",
  HEADER_UNMAPPED: "HEADER_UNMAPPED",
  VALUE_INVALID: "VALUE_INVALID",
  UNSUPPORTED_HANDICAP: "UNSUPPORTED_HANDICAP",
  TERMINATION_NOT_FOUND: "TERMINATION_NOT_FOUND",
  RESULT_UNKNOWN: "RESULT_UNKNOWN",
  PLAYER_SIDE_REQUIRED: "PLAYER_SIDE_REQUIRED",
  ENCODING_EXTENSION_MISMATCH: "ENCODING_EXTENSION_MISMATCH",
  MOVE_HEADER_OMITTED: "MOVE_HEADER_OMITTED"
});

export class KifImportError extends Error {
  constructor(code, userMessage, context = {}, options = {}) {
    super(userMessage, options);
    this.name = "KifImportError";
    this.code = code;
    this.userMessage = userMessage;
    this.context = Object.freeze({ ...context });
  }
}

export function createKifImportWarning(code, message, context = {}) {
  return Object.freeze({
    severity: "WARNING",
    code,
    message,
    context: Object.freeze({ ...context })
  });
}
