function createCodeMap(definition) {
  if (
    definition === null ||
    typeof definition !== "object" ||
    Array.isArray(definition)
  ) {
    throw new TypeError("Code map definition must be a plain object.");
  }

  return Object.freeze({ ...definition });
}

export const PLAN_VERSION_STATUS = createCodeMap({
  DRAFT: "DRAFT",
  REVIEW: "REVIEW",
  APPROVED: "APPROVED",
  SUPERSEDED: "SUPERSEDED",
  ARCHIVED: "ARCHIVED"
});

export const ASSUMPTION_STATUS = createCodeMap({
  UNKNOWN: "UNKNOWN",
  EXPECTED: "EXPECTED",
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED"
});

export const ASSUMPTION_CONFIDENCE = createCodeMap({
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW"
});

export const ASSUMPTION_TYPE = createCodeMap({
  MATERIAL_ARRIVAL: "MATERIAL_ARRIVAL",
  PREVIOUS_OPERATION_COMPLETION: "PREVIOUS_OPERATION_COMPLETION",
  EQUIPMENT_AVAILABILITY: "EQUIPMENT_AVAILABILITY",
  WORKER_AVAILABILITY: "WORKER_AVAILABILITY",
  SKILL_AVAILABILITY: "SKILL_AVAILABILITY",
  TRANSPORT_AVAILABILITY: "TRANSPORT_AVAILABILITY",
  QUALITY_RELEASE: "QUALITY_RELEASE",
  STORAGE_SPACE: "STORAGE_SPACE",
  OUTSOURCING_AVAILABILITY: "OUTSOURCING_AVAILABILITY",
  INFORMATION_FRESHNESS: "INFORMATION_FRESHNESS",
  OTHER: "OTHER"
});

export const ASSUMPTION_TARGET_TYPE = createCodeMap({
  PRODUCTION_PLAN: "PRODUCTION_PLAN",
  PLAN_VERSION: "PLAN_VERSION",
  PLANNED_OPERATION: "PLANNED_OPERATION",
  ORDER: "ORDER",
  ROUTING_OPERATION: "ROUTING_OPERATION",
  FACTORY: "FACTORY",
  PROCESS: "PROCESS",
  EQUIPMENT: "EQUIPMENT",
  SHIFT: "SHIFT",
  WORKER: "WORKER",
  SKILL: "SKILL",
  MATERIAL: "MATERIAL",
  TRANSPORT: "TRANSPORT"
});

export const ASSUMPTION_EVIDENCE_TYPE = createCodeMap({
  SYSTEM_RECORD: "SYSTEM_RECORD",
  DOCUMENT: "DOCUMENT",
  EMAIL: "EMAIL",
  INTERVIEW: "INTERVIEW",
  OBSERVATION: "OBSERVATION",
  CALCULATION: "CALCULATION",
  EXTERNAL_CONFIRMATION: "EXTERNAL_CONFIRMATION",
  OTHER: "OTHER"
});

export const ASSUMPTION_IMPACT_LEVEL = createCodeMap({
  CRITICAL: "CRITICAL",
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW"
});

export const ASSUMPTION_EFFECTIVE_STATUS = createCodeMap({
  UNKNOWN: "UNKNOWN",
  EXPECTED: "EXPECTED",
  EFFECTIVE_CONFIRMED: "EFFECTIVE_CONFIRMED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  OUTSIDE_VALIDITY: "OUTSIDE_VALIDITY"
});

export const DIAGNOSIS_STATUS = createCodeMap({
  FEASIBLE: "FEASIBLE",
  PARTIALLY_FEASIBLE: "PARTIALLY_FEASIBLE",
  INFEASIBLE: "INFEASIBLE",
  UNKNOWN: "UNKNOWN"
});

export const CAPACITY_STATUS = createCodeMap({
  FEASIBLE: "FEASIBLE",
  PARTIALLY_FEASIBLE: "PARTIALLY_FEASIBLE",
  INFEASIBLE: "INFEASIBLE",
  UNKNOWN: "UNKNOWN"
});

export const RESULT_VALIDITY_STATUS = createCodeMap({
  CURRENT: "CURRENT",
  STALE: "STALE",
  INVALID: "INVALID"
});

export const MODEL_COVERAGE_STATUS = createCodeMap({
  MODELED: "MODELED",
  PARTIALLY_MODELED: "PARTIALLY_MODELED",
  UNMODELED: "UNMODELED"
});

export const CONDITION_COVERAGE_TYPE = createCodeMap({
  DIRECT_MODEL: "DIRECT_MODEL",
  ASSUMPTION: "ASSUMPTION",
  UNMODELED: "UNMODELED"
});

export const ROUTING_STATUS = createCodeMap({
  VALID: "VALID",
  INVALID: "INVALID",
  UNKNOWN: "UNKNOWN",
  NOT_APPLICABLE: "NOT_APPLICABLE"
});

export const ROUTING_CHECK_DIRECTION = createCodeMap({
  PREVIOUS: "PREVIOUS",
  NEXT: "NEXT"
});

export const ROUTING_CHECK_REASON = createCodeMap({
  PREVIOUS_OPERATION_ON_EARLIER_DATE: "PREVIOUS_OPERATION_ON_EARLIER_DATE",
  PREVIOUS_OPERATION_PLANNED_AFTER_CURRENT: "PREVIOUS_OPERATION_PLANNED_AFTER_CURRENT",
  PREVIOUS_OPERATION_ENDS_BEFORE_CURRENT: "PREVIOUS_OPERATION_ENDS_BEFORE_CURRENT",
  PREVIOUS_OPERATION_OVERLAPS_CURRENT: "PREVIOUS_OPERATION_OVERLAPS_CURRENT",
  PREVIOUS_SHIFT_BEFORE_CURRENT: "PREVIOUS_SHIFT_BEFORE_CURRENT",
  PREVIOUS_SHIFT_AFTER_CURRENT: "PREVIOUS_SHIFT_AFTER_CURRENT",
  NEXT_OPERATION_ON_LATER_DATE: "NEXT_OPERATION_ON_LATER_DATE",
  NEXT_OPERATION_PLANNED_BEFORE_CURRENT: "NEXT_OPERATION_PLANNED_BEFORE_CURRENT",
  NEXT_OPERATION_STARTS_AFTER_CURRENT: "NEXT_OPERATION_STARTS_AFTER_CURRENT",
  NEXT_OPERATION_OVERLAPS_CURRENT: "NEXT_OPERATION_OVERLAPS_CURRENT",
  NEXT_SHIFT_AFTER_CURRENT: "NEXT_SHIFT_AFTER_CURRENT",
  NEXT_SHIFT_BEFORE_CURRENT: "NEXT_SHIFT_BEFORE_CURRENT",
  SAME_DAY_SEQUENCE_UNCONFIRMED: "SAME_DAY_SEQUENCE_UNCONFIRMED",
  ADJACENT_OPERATION_NOT_PLANNED: "ADJACENT_OPERATION_NOT_PLANNED",
  ROUTING_DEFINITION_NOT_FOUND: "ROUTING_DEFINITION_NOT_FOUND"
});

export const ASSUMPTION_RESOLUTION_STATUS = createCodeMap({
  SATISFIED: "SATISFIED",
  UNRESOLVED: "UNRESOLVED",
  REJECTED: "REJECTED",
  CONFLICT: "CONFLICT",
  NOT_APPLICABLE: "NOT_APPLICABLE"
});

export const DIAGNOSIS_SCENARIO_CATEGORY = createCodeMap({
  BASE: "BASE",
  COMPARISON: "COMPARISON",
  EXPERIMENT: "EXPERIMENT",
  ARCHIVED: "ARCHIVED"
});


export const SCENARIO_COMPARISON_OUTCOME = createCodeMap({
  IMPROVED: "IMPROVED",
  WORSENED: "WORSENED",
  UNCHANGED: "UNCHANGED",
  MIXED: "MIXED",
  UNCERTAIN: "UNCERTAIN",
  NOT_COMPARABLE: "NOT_COMPARABLE"
});

export const OPERATION_COMPARISON_OUTCOME = createCodeMap({
  IMPROVED: "IMPROVED",
  WORSENED: "WORSENED",
  UNCHANGED: "UNCHANGED",
  MIXED: "MIXED",
  UNCERTAIN: "UNCERTAIN",
  ADDED: "ADDED",
  REMOVED: "REMOVED"
});

export const CAPACITY_BASELINE = createCodeMap({
  AVAILABLE_CAPACITY: "AVAILABLE_CAPACITY",
  REMAINING_AFTER_BASELINE: "REMAINING_AFTER_BASELINE"
});

export const DIAGNOSIS_GRANULARITY = createCodeMap({
  DAY: "DAY",
  SHIFT: "SHIFT",
  TIME: "TIME",
  UNAVAILABLE: "UNAVAILABLE"
});

export const QUANTITY_UNIT = createCodeMap({
  PIECE: "PIECE",
  KILOGRAM: "KILOGRAM",
  LOT: "LOT"
});

export const EQUIPMENT_AVAILABILITY_STATUS = createCodeMap({
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE",
  UNKNOWN: "UNKNOWN"
});

export const CAPACITY_RESOURCE_STATUS = createCodeMap({
  SATISFIED: "SATISFIED",
  PARTIALLY_SATISFIED: "PARTIALLY_SATISFIED",
  UNSATISFIED: "UNSATISFIED",
  UNKNOWN: "UNKNOWN"
});

export const CAPACITY_RATE_BASIS = createCodeMap({
  HOUR: "HOUR",
  SHIFT: "SHIFT",
  DAY: "DAY"
});

export const CONSTRAINT_SEVERITY = createCodeMap({
  CRITICAL: "CRITICAL",
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  INFO: "INFO"
});

export const CONSTRAINT_CATEGORY = createCodeMap({
  CAPACITY: "CAPACITY",
  EQUIPMENT: "EQUIPMENT",
  WORKER: "WORKER",
  SKILL: "SKILL",
  ASSIGNMENT: "ASSIGNMENT",
  ROUTING: "ROUTING",
  ASSUMPTION: "ASSUMPTION",
  MATERIAL: "MATERIAL",
  TRANSPORT: "TRANSPORT",
  QUALITY: "QUALITY",
  MODEL_COVERAGE: "MODEL_COVERAGE",
  DATA: "DATA",
  OTHER: "OTHER"
});

export const FINDING_CONFIRMATION_STATUS = createCodeMap({
  CONFIRMED: "CONFIRMED",
  INFERRED: "INFERRED",
  POSSIBLE: "POSSIBLE",
  UNKNOWN: "UNKNOWN"
});

export const FINDING_SOURCE_TYPE = createCodeMap({
  CAPACITY_ALLOCATION: "CAPACITY_ALLOCATION",
  CAPACITY_RULE: "CAPACITY_RULE",
  ROUTING_DIAGNOSIS: "ROUTING_DIAGNOSIS",
  ASSUMPTION_RESOLUTION: "ASSUMPTION_RESOLUTION",
  MODEL_COVERAGE: "MODEL_COVERAGE",
  CONFIRMED_CONSTRAINT: "CONFIRMED_CONSTRAINT",
  DATA_VALIDATION: "DATA_VALIDATION",
  OTHER: "OTHER"
});

export const DATA_CONFIDENCE = createCodeMap({
  A: "A",
  B: "B",
  C: "C",
  D: "D"
});

export const CAPACITY_RULE_RESOLUTION_STATUS = createCodeMap({
  RESOLVED: "RESOLVED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT"
});

export const CAPACITY_RULE_SOURCE = createCodeMap({
  OPERATION_OVERRIDE: "OPERATION_OVERRIDE",
  ORDER_ATTRIBUTE: "ORDER_ATTRIBUTE",
  DEFAULT_RULE: "DEFAULT_RULE",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT"
});

export const OPERATION_STATUS_REASON = createCodeMap({
  ALL_CONDITIONS_SATISFIED: "ALL_CONDITIONS_SATISFIED",
  CAPACITY_PARTIAL: "CAPACITY_PARTIAL",
  BLOCKING_ASSUMPTION_REJECTED: "BLOCKING_ASSUMPTION_REJECTED",
  CONFIRMED_CONSTRAINT: "CONFIRMED_CONSTRAINT",
  ROUTING_INVALID: "ROUTING_INVALID",
  CAPACITY_INFEASIBLE: "CAPACITY_INFEASIBLE",
  ASSUMPTION_CONFLICT: "ASSUMPTION_CONFLICT",
  BLOCKING_ASSUMPTION_UNRESOLVED: "BLOCKING_ASSUMPTION_UNRESOLVED",
  CAPACITY_UNKNOWN: "CAPACITY_UNKNOWN",
  ROUTING_UNKNOWN: "ROUTING_UNKNOWN",
  MODEL_COVERAGE_UNKNOWN: "MODEL_COVERAGE_UNKNOWN"
});

export const IMPORT_PREVIEW_STATUS = createCodeMap({
  ADD: "ADD",
  UPDATE: "UPDATE",
  UNCHANGED: "UNCHANGED",
  DUPLICATE: "DUPLICATE",
  ERROR: "ERROR",
  WARNING: "WARNING"
});

export const IMPORT_BATCH_STATUS = createCodeMap({
  RECEIVED: "RECEIVED",
  PARSING: "PARSING",
  PREVIEWED: "PREVIEWED",
  COMMIT_READY: "COMMIT_READY",
  COMMITTED: "COMMITTED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED"
});

export const IMPORT_ISSUE_SEVERITY = createCodeMap({
  ERROR: "ERROR",
  WARNING: "WARNING",
  INFO: "INFO"
});

export const IMPORT_ISSUE_CODE = createCodeMap({
  EMPTY_FILE: "EMPTY_FILE",
  CSV_PARSE_FAILED: "CSV_PARSE_FAILED",
  REQUIRED_HEADER_MISSING: "REQUIRED_HEADER_MISSING",
  UNKNOWN_HEADER: "UNKNOWN_HEADER",
  DUPLICATE_HEADER: "DUPLICATE_HEADER",
  COLUMN_COUNT_MISMATCH: "COLUMN_COUNT_MISMATCH",
  REQUIRED_VALUE_MISSING: "REQUIRED_VALUE_MISSING",
  INVALID_VALUE: "INVALID_VALUE",
  DUPLICATE_ROW_ID: "DUPLICATE_ROW_ID",
  TARGET_VERSION_MISMATCH: "TARGET_VERSION_MISMATCH",
  TARGET_VERSION_NOT_FOUND: "TARGET_VERSION_NOT_FOUND",
  TARGET_VERSION_NOT_EDITABLE: "TARGET_VERSION_NOT_EDITABLE",
  EXISTING_ENTITY_VERSION_MISMATCH: "EXISTING_ENTITY_VERSION_MISMATCH",
  EXISTING_ENTITY_SCOPE_MISMATCH: "EXISTING_ENTITY_SCOPE_MISMATCH",
  TARGET_CONTEXT_MISMATCH: "TARGET_CONTEXT_MISMATCH",
  BASE_SCENARIO_NOT_FOUND: "BASE_SCENARIO_NOT_FOUND",
  ENTITY_VALIDATION_FAILED: "ENTITY_VALIDATION_FAILED",
  EXISTING_ENTITY_UPDATE: "EXISTING_ENTITY_UPDATE",
  UNCHANGED_ROW: "UNCHANGED_ROW"
});

export const NEXT_CHECK_STATUS = createCodeMap({
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  NOT_REQUIRED: "NOT_REQUIRED",
  CANNOT_CONFIRM: "CANNOT_CONFIRM"
});

export const NEXT_CHECK_TYPE = createCodeMap({
  CONFIRM_ASSUMPTION: "CONFIRM_ASSUMPTION",
  VERIFY_CAPACITY_DATA: "VERIFY_CAPACITY_DATA",
  RESOLVE_CAPACITY_RULE: "RESOLVE_CAPACITY_RULE",
  VERIFY_ROUTING: "VERIFY_ROUTING",
  REGISTER_MISSING_OPERATION: "REGISTER_MISSING_OPERATION",
  RESOLVE_MODEL_GAP: "RESOLVE_MODEL_GAP",
  CORRECT_PLAN: "CORRECT_PLAN",
  OTHER: "OTHER"
});

export const NEXT_CHECK_PRIORITY = createCodeMap({
  CRITICAL: "CRITICAL",
  HIGH: "HIGH",
  NORMAL: "NORMAL",
  LOW: "LOW"
});

export const NEXT_CHECK_SOURCE_TYPE = createCodeMap({
  CONSTRAINT_FINDING: "CONSTRAINT_FINDING",
  ASSUMPTION_FINDING: "ASSUMPTION_FINDING",
  MODEL_COVERAGE: "MODEL_COVERAGE",
  DIAGNOSIS_RESULT: "DIAGNOSIS_RESULT",
  OTHER: "OTHER"
});


export const STALE_REASON_CODE = createCodeMap({
  DIAGNOSIS_SCENARIO_CHANGED: "DIAGNOSIS_SCENARIO_CHANGED",
  PLAN_VERSION_CHANGED: "PLAN_VERSION_CHANGED",
  CAPACITY_SCENARIO_CHANGED: "CAPACITY_SCENARIO_CHANGED",
  TARGET_MONTH_CHANGED: "TARGET_MONTH_CHANGED",
  CAPACITY_REVISION_CHANGED: "CAPACITY_REVISION_CHANGED",
  CALENDAR_REVISION_CHANGED: "CALENDAR_REVISION_CHANGED",
  ASSIGNMENT_REVISION_CHANGED: "ASSIGNMENT_REVISION_CHANGED",
  CAPACITY_RULE_REVISION_CHANGED: "CAPACITY_RULE_REVISION_CHANGED",
  EQUIPMENT_REVISION_CHANGED: "EQUIPMENT_REVISION_CHANGED",
  WORKER_REVISION_CHANGED: "WORKER_REVISION_CHANGED",
  SKILL_REVISION_CHANGED: "SKILL_REVISION_CHANGED",
  PLANNED_OPERATION_CHANGED: "PLANNED_OPERATION_CHANGED",
  ASSUMPTION_CHANGED: "ASSUMPTION_CHANGED",
  ROUTING_CHANGED: "ROUTING_CHANGED",
  MODEL_COVERAGE_CHANGED: "MODEL_COVERAGE_CHANGED",
  DIAGNOSIS_INPUT_REVISION_CHANGED: "DIAGNOSIS_INPUT_REVISION_CHANGED",
  CAPACITY_SOURCE_REVISION_CHANGED: "CAPACITY_SOURCE_REVISION_CHANGED",
  SOURCE_REVISION_SCHEMA_CHANGED: "SOURCE_REVISION_SCHEMA_CHANGED",
  SOURCE_REVISION_REGRESSION: "SOURCE_REVISION_REGRESSION"
});

export const REVISION_SOURCE_TYPE = createCodeMap({
  CAPACITY_SOURCE: "CAPACITY_SOURCE",
  DIAGNOSIS_INPUT: "DIAGNOSIS_INPUT",
  SOURCE_IDENTITY: "SOURCE_IDENTITY"
});

export const REVISION_CHANGE_TYPE = createCodeMap({
  VALUE_CHANGED: "VALUE_CHANGED",
  KEY_ADDED: "KEY_ADDED",
  KEY_REMOVED: "KEY_REMOVED",
  REVISION_REGRESSION: "REVISION_REGRESSION",
  IDENTITY_CHANGED: "IDENTITY_CHANGED"
});

export const FIELD_IMPACT_CLASSIFICATION = createCodeMap({
  DIAGNOSIS_AFFECTING: "DIAGNOSIS_AFFECTING",
  PRESENTATION_ONLY: "PRESENTATION_ONLY",
  AUDIT_ONLY: "AUDIT_ONLY"
});

export const ACTOR_TYPE = createCodeMap({
  USER: "USER",
  SYSTEM: "SYSTEM",
  IMPORT: "IMPORT",
  EXTERNAL_ADAPTER: "EXTERNAL_ADAPTER"
});

export const ID_NAMESPACE = createCodeMap({
  PRODUCTION_PLAN: "PRODUCTION_PLAN",
  PLAN_VERSION: "PLAN_VERSION",
  PLANNED_OPERATION: "PLANNED_OPERATION",
  ASSUMPTION: "ASSUMPTION",
  DIAGNOSIS_SCENARIO: "DIAGNOSIS_SCENARIO",
  IMPORT_BATCH: "IMPORT_BATCH",
  EVENT: "EVENT",
  CORRELATION: "CORRELATION",
  CAPACITY_ALLOCATION: "CAPACITY_ALLOCATION",
  CONSTRAINT_FINDING: "CONSTRAINT_FINDING",
  ASSUMPTION_FINDING: "ASSUMPTION_FINDING",
  NEXT_CHECK: "NEXT_CHECK",
  OPERATION_DIAGNOSIS_RESULT: "OPERATION_DIAGNOSIS_RESULT",
  DIAGNOSIS_SUMMARY: "DIAGNOSIS_SUMMARY",
  DIAGNOSIS_RESULT: "DIAGNOSIS_RESULT"
});

export const CODE_CATALOG = Object.freeze({
  PLAN_VERSION_STATUS,
  ASSUMPTION_STATUS,
  ASSUMPTION_CONFIDENCE,
  ASSUMPTION_TYPE,
  ASSUMPTION_TARGET_TYPE,
  ASSUMPTION_EVIDENCE_TYPE,
  ASSUMPTION_IMPACT_LEVEL,
  ASSUMPTION_EFFECTIVE_STATUS,
  DIAGNOSIS_STATUS,
  CAPACITY_STATUS,
  RESULT_VALIDITY_STATUS,
  MODEL_COVERAGE_STATUS,
  CONDITION_COVERAGE_TYPE,
  ROUTING_STATUS,
  ROUTING_CHECK_DIRECTION,
  ROUTING_CHECK_REASON,
  ASSUMPTION_RESOLUTION_STATUS,
  DIAGNOSIS_SCENARIO_CATEGORY,
  SCENARIO_COMPARISON_OUTCOME,
  OPERATION_COMPARISON_OUTCOME,
  CAPACITY_BASELINE,
  DIAGNOSIS_GRANULARITY,
  QUANTITY_UNIT,
  EQUIPMENT_AVAILABILITY_STATUS,
  CAPACITY_RESOURCE_STATUS,
  CAPACITY_RATE_BASIS,
  CONSTRAINT_SEVERITY,
  CONSTRAINT_CATEGORY,
  FINDING_CONFIRMATION_STATUS,
  FINDING_SOURCE_TYPE,
  DATA_CONFIDENCE,
  CAPACITY_RULE_RESOLUTION_STATUS,
  CAPACITY_RULE_SOURCE,
  OPERATION_STATUS_REASON,
  IMPORT_PREVIEW_STATUS,
  IMPORT_BATCH_STATUS,
  IMPORT_ISSUE_SEVERITY,
  IMPORT_ISSUE_CODE,
  NEXT_CHECK_STATUS,
  NEXT_CHECK_TYPE,
  NEXT_CHECK_PRIORITY,
  NEXT_CHECK_SOURCE_TYPE,
  STALE_REASON_CODE,
  REVISION_SOURCE_TYPE,
  REVISION_CHANGE_TYPE,
  FIELD_IMPACT_CLASSIFICATION,
  ACTOR_TYPE,
  ID_NAMESPACE
});

export function assertCodeMap(codeMap) {
  if (
    codeMap === null ||
    typeof codeMap !== "object" ||
    Array.isArray(codeMap)
  ) {
    throw new TypeError("codeMap must be a code map object.");
  }

  return codeMap;
}

export function getCodeValues(codeMap) {
  assertCodeMap(codeMap);
  return Object.freeze(Object.values(codeMap));
}

export function isCodeValue(codeMap, value) {
  return getCodeValues(codeMap).includes(value);
}
