import {
  getCodeValues,
  isCodeValue
} from "./DiagnosisCodes.js";

function createCodeMap(definition) {
  return Object.freeze({ ...definition });
}

export const ERROR_CATEGORY = createCodeMap({
  DOMAIN: "DOMAIN",
  APPLICATION: "APPLICATION",
  IMPORT: "IMPORT",
  REPOSITORY: "REPOSITORY",
  PRESENTATION: "PRESENTATION",
  UNEXPECTED: "UNEXPECTED"
});

/**
 * DAY29のerrors.jsで確立したERROR_CODES＋ApplicationError形式を継承し、
 * DAY30固有の計画診断・Assumption・Import・Stale判定へ拡張する。
 */
export const ERROR_CODES = createCodeMap({
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  INVALID_CODE_VALUE: "INVALID_CODE_VALUE",
  INVALID_NON_EMPTY_STRING: "INVALID_NON_EMPTY_STRING",
  INVALID_BOOLEAN: "INVALID_BOOLEAN",
  INVALID_POSITIVE_INTEGER: "INVALID_POSITIVE_INTEGER",
  INVALID_NON_NEGATIVE_INTEGER: "INVALID_NON_NEGATIVE_INTEGER",
  INVALID_FINITE_NUMBER: "INVALID_FINITE_NUMBER",
  INVALID_ARRAY: "INVALID_ARRAY",
  INVALID_PLAIN_OBJECT: "INVALID_PLAIN_OBJECT",

  INVALID_PLAN_ID: "INVALID_PLAN_ID",
  INVALID_PLAN_VERSION_ID: "INVALID_PLAN_VERSION_ID",
  INVALID_PLANNED_OPERATION_ID: "INVALID_PLANNED_OPERATION_ID",
  INVALID_ASSUMPTION_ID: "INVALID_ASSUMPTION_ID",
  INVALID_DIAGNOSIS_SCENARIO_ID: "INVALID_DIAGNOSIS_SCENARIO_ID",

  INVALID_TARGET_MONTH: "INVALID_TARGET_MONTH",
  INVALID_DATE: "INVALID_DATE",
  INVALID_TIME: "INVALID_TIME",
  INVALID_DATE_TIME: "INVALID_DATE_TIME",
  INVALID_TIME_RANGE: "INVALID_TIME_RANGE",
  INCOMPLETE_TIME_RANGE: "INCOMPLETE_TIME_RANGE",

  INVALID_PLAN_VERSION_STATUS: "INVALID_PLAN_VERSION_STATUS",
  INVALID_PLAN_VERSION_TRANSITION: "INVALID_PLAN_VERSION_TRANSITION",
  PLAN_VERSION_NOT_EDITABLE: "PLAN_VERSION_NOT_EDITABLE",
  SOURCE_VERSION_SELF_REFERENCE: "SOURCE_VERSION_SELF_REFERENCE",

  INVALID_PLANNED_QUANTITY: "INVALID_PLANNED_QUANTITY",
  INVALID_QUANTITY_UNIT: "INVALID_QUANTITY_UNIT",
  INVALID_PRIORITY: "INVALID_PRIORITY",

  INVALID_ASSUMPTION_STATUS: "INVALID_ASSUMPTION_STATUS",
  INVALID_ASSUMPTION_TRANSITION: "INVALID_ASSUMPTION_TRANSITION",
  CONFIRMED_AT_REQUIRED: "CONFIRMED_AT_REQUIRED",
  REJECTED_AT_REQUIRED: "REJECTED_AT_REQUIRED",
  INVALID_VALIDITY_PERIOD: "INVALID_VALIDITY_PERIOD",

  INVALID_DIAGNOSIS_SCENARIO: "INVALID_DIAGNOSIS_SCENARIO",
  INVALID_CAPACITY_BASELINE: "INVALID_CAPACITY_BASELINE",
  UNSUPPORTED_CAPACITY_BASELINE: "UNSUPPORTED_CAPACITY_BASELINE",
  BASE_SCENARIO_SELF_REFERENCE: "BASE_SCENARIO_SELF_REFERENCE",
  COMPARISON_BASE_REQUIRED: "COMPARISON_BASE_REQUIRED",
  CHANGE_SUMMARY_REQUIRED: "CHANGE_SUMMARY_REQUIRED",

  CAPACITY_RULE_NOT_FOUND: "CAPACITY_RULE_NOT_FOUND",
  CAPACITY_RULE_CONFLICT: "CAPACITY_RULE_CONFLICT",
  CAPACITY_UNIT_MISMATCH: "CAPACITY_UNIT_MISMATCH",
  CAPACITY_BUCKET_NOT_FOUND: "CAPACITY_BUCKET_NOT_FOUND",
  CAPACITY_ALLOCATION_EXCEEDED: "CAPACITY_ALLOCATION_EXCEEDED",

  DIAGNOSIS_SOURCE_INCONSISTENT: "DIAGNOSIS_SOURCE_INCONSISTENT",
  DIAGNOSIS_SOURCE_CHANGED_DURING_EXECUTION:
    "DIAGNOSIS_SOURCE_CHANGED_DURING_EXECUTION",
  READ_MODEL_INTEGRITY_ERROR: "READ_MODEL_INTEGRITY_ERROR",

  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  REPOSITORY_CONTRACT_VIOLATION: "REPOSITORY_CONTRACT_VIOLATION",

  IMPORT_VALIDATION_FAILED: "IMPORT_VALIDATION_FAILED",
  IMPORT_STALE_PREVIEW: "IMPORT_STALE_PREVIEW",
  IMPORT_COMMIT_NOT_ALLOWED: "IMPORT_COMMIT_NOT_ALLOWED",
  IMPORT_TRANSACTION_FAILED: "IMPORT_TRANSACTION_FAILED",
  INVALID_CSV_TEXT: "INVALID_CSV_TEXT",
  CSV_PARSE_ERROR: "CSV_PARSE_ERROR",
  CSV_HEADER_VALIDATION_FAILED: "CSV_HEADER_VALIDATION_FAILED",
  INVALID_IMPORT_BATCH_ID: "INVALID_IMPORT_BATCH_ID",
  INVALID_IMPORT_PREVIEW: "INVALID_IMPORT_PREVIEW",
  INVALID_IMPORT_ROW: "INVALID_IMPORT_ROW",
  IMPORT_TARGET_VERSION_MISMATCH: "IMPORT_TARGET_VERSION_MISMATCH",
  IMPORT_TARGET_VERSION_NOT_FOUND: "IMPORT_TARGET_VERSION_NOT_FOUND",
  IMPORT_TARGET_VERSION_NOT_EDITABLE: "IMPORT_TARGET_VERSION_NOT_EDITABLE",

  PRESENTATION_TARGET_NOT_FOUND: "PRESENTATION_TARGET_NOT_FOUND",
  INVALID_DASHBOARD_VIEW_MODEL: "INVALID_DASHBOARD_VIEW_MODEL",
  INVALID_DASHBOARD_SELECTION: "INVALID_DASHBOARD_SELECTION",
  INVALID_DIAGNOSIS_BROWSER_CONTROLLER: "INVALID_DIAGNOSIS_BROWSER_CONTROLLER",
  INVALID_DIAGNOSIS_DOM_RENDERER: "INVALID_DIAGNOSIS_DOM_RENDERER",
  INVALID_PLANNED_OPERATION_CSV_IMPORT_CONTROLLER:
    "INVALID_PLANNED_OPERATION_CSV_IMPORT_CONTROLLER",
  INVALID_ENTITY_CSV_IMPORT_CONTROLLER:
    "INVALID_ENTITY_CSV_IMPORT_CONTROLLER",
  DIAGNOSIS_DOM_ROOT_NOT_FOUND: "DIAGNOSIS_DOM_ROOT_NOT_FOUND",
  STALE_PRESENTATION_REQUEST: "STALE_PRESENTATION_REQUEST",
  UNSUPPORTED_ROUTE: "UNSUPPORTED_ROUTE",
  CAPACITY_ALLOCATION_TARGET_AMBIGUOUS: "CAPACITY_ALLOCATION_TARGET_AMBIGUOUS",
  CAPACITY_LEDGER_NOT_FOUND: "CAPACITY_LEDGER_NOT_FOUND",
  DIAGNOSIS_SCENARIO_ALREADY_ACTIVE: "DIAGNOSIS_SCENARIO_ALREADY_ACTIVE",
  DIAGNOSIS_SCENARIO_ALREADY_INACTIVE: "DIAGNOSIS_SCENARIO_ALREADY_INACTIVE",
  DIAGNOSIS_SCENARIO_ARCHIVED: "DIAGNOSIS_SCENARIO_ARCHIVED",
  DUPLICATE_CAPACITY_ALLOCATION: "DUPLICATE_CAPACITY_ALLOCATION",
  DUPLICATE_CAPACITY_BUCKET: "DUPLICATE_CAPACITY_BUCKET",
  DUPLICATE_DOMAIN_EVENT: "DUPLICATE_DOMAIN_EVENT",
  DUPLICATE_ID_PREFIX: "DUPLICATE_ID_PREFIX",
  DUPLICATE_OPERATION_DIAGNOSIS_RESULT: "DUPLICATE_OPERATION_DIAGNOSIS_RESULT",
  EVENT_CAUSATION_SELF_REFERENCE: "EVENT_CAUSATION_SELF_REFERENCE",
  INVALID_ASSUMPTION_CONFIDENCE: "INVALID_ASSUMPTION_CONFIDENCE",
  INVALID_ASSUMPTION_EVIDENCE: "INVALID_ASSUMPTION_EVIDENCE",
  INVALID_ASSUMPTION_FINDING: "INVALID_ASSUMPTION_FINDING",
  INVALID_ASSUMPTION_IMPACT_LEVEL: "INVALID_ASSUMPTION_IMPACT_LEVEL",
  INVALID_ASSUMPTION_RESOLUTION: "INVALID_ASSUMPTION_RESOLUTION",
  INVALID_ASSUMPTION_STATE: "INVALID_ASSUMPTION_STATE",
  INVALID_ASSUMPTION_TARGET: "INVALID_ASSUMPTION_TARGET",
  INVALID_ASSUMPTION_TEXT: "INVALID_ASSUMPTION_TEXT",
  INVALID_ASSUMPTION_TYPE: "INVALID_ASSUMPTION_TYPE",
  INVALID_CAPACITY_ALLOCATION: "INVALID_CAPACITY_ALLOCATION",
  INVALID_CAPACITY_ALLOCATION_REQUEST: "INVALID_CAPACITY_ALLOCATION_REQUEST",
  INVALID_CAPACITY_BUCKET: "INVALID_CAPACITY_BUCKET",
  INVALID_CAPACITY_BUCKET_STATE: "INVALID_CAPACITY_BUCKET_STATE",
  INVALID_CAPACITY_LEDGER: "INVALID_CAPACITY_LEDGER",
  INVALID_CAPACITY_MULTIPLIER: "INVALID_CAPACITY_MULTIPLIER",
  INVALID_CAPACITY_REASON_CODE: "INVALID_CAPACITY_REASON_CODE",
  INVALID_CAPACITY_RULE: "INVALID_CAPACITY_RULE",
  INVALID_CAPACITY_SCENARIO_ID: "INVALID_CAPACITY_SCENARIO_ID",
  INVALID_CAPACITY_SNAPSHOT: "INVALID_CAPACITY_SNAPSHOT",
  INVALID_CAPACITY_VALUE: "INVALID_CAPACITY_VALUE",
  INVALID_CONFIRMED_CONSTRAINT: "INVALID_CONFIRMED_CONSTRAINT",
  INVALID_CONSTRAINT_FINDING: "INVALID_CONSTRAINT_FINDING",
  INVALID_DIAGNOSIS_ENGINE: "INVALID_DIAGNOSIS_ENGINE",
  INVALID_DIAGNOSIS_RESULT: "INVALID_DIAGNOSIS_RESULT",
  INVALID_DIAGNOSIS_SCENARIO_CATEGORY: "INVALID_DIAGNOSIS_SCENARIO_CATEGORY",
  INVALID_DIAGNOSIS_SCENARIO_NAME: "INVALID_DIAGNOSIS_SCENARIO_NAME",
  INVALID_DIAGNOSIS_SCENARIO_STATE: "INVALID_DIAGNOSIS_SCENARIO_STATE",
  INVALID_DIAGNOSIS_SCENARIO_TEXT: "INVALID_DIAGNOSIS_SCENARIO_TEXT",
  INVALID_DIAGNOSIS_SUMMARY: "INVALID_DIAGNOSIS_SUMMARY",
  INVALID_SCENARIO_COMPARISON: "INVALID_SCENARIO_COMPARISON",
  SCENARIO_COMPARISON_NOT_AVAILABLE: "SCENARIO_COMPARISON_NOT_AVAILABLE",
  INVALID_DOMAIN_EVENT: "INVALID_DOMAIN_EVENT",
  INVALID_DOMAIN_EVENT_COLLECTOR: "INVALID_DOMAIN_EVENT_COLLECTOR",
  INVALID_EQUIPMENT_ID: "INVALID_EQUIPMENT_ID",
  INVALID_EVENT_ACTOR: "INVALID_EVENT_ACTOR",
  INVALID_EVENT_DATA: "INVALID_EVENT_DATA",
  INVALID_EVENT_ID: "INVALID_EVENT_ID",
  INVALID_EVENT_TIME_ORDER: "INVALID_EVENT_TIME_ORDER",
  INVALID_EVENT_TYPE: "INVALID_EVENT_TYPE",
  INVALID_EVENT_VERSION: "INVALID_EVENT_VERSION",
  INVALID_FACTORY_ID: "INVALID_FACTORY_ID",
  INVALID_FINDING_METRICS: "INVALID_FINDING_METRICS",
  INVALID_FINDING_SOURCE: "INVALID_FINDING_SOURCE",
  INVALID_GENERATED_ID: "INVALID_GENERATED_ID",
  INVALID_ID_COUNTER: "INVALID_ID_COUNTER",
  INVALID_ID_NAMESPACE: "INVALID_ID_NAMESPACE",
  INVALID_ID_PREFIX: "INVALID_ID_PREFIX",
  INVALID_MODEL_CONDITION: "INVALID_MODEL_CONDITION",
  INVALID_MODEL_COVERAGE_EVALUATION: "INVALID_MODEL_COVERAGE_EVALUATION",
  INVALID_NEXT_CHECK: "INVALID_NEXT_CHECK",
  INVALID_NEXT_CHECK_STATE: "INVALID_NEXT_CHECK_STATE",
  INVALID_OPERATION_CONDITION: "INVALID_OPERATION_CONDITION",
  INVALID_OPERATION_DIAGNOSIS_RESULT: "INVALID_OPERATION_DIAGNOSIS_RESULT",
  INVALID_OPERATION_DIMENSION: "INVALID_OPERATION_DIMENSION",
  INVALID_OPERATION_STATUS_DECISION: "INVALID_OPERATION_STATUS_DECISION",
  INVALID_ORDER_ID: "INVALID_ORDER_ID",
  INVALID_PLANNED_OPERATION_TEXT: "INVALID_PLANNED_OPERATION_TEXT",
  INVALID_PLAN_NAME: "INVALID_PLAN_NAME",
  INVALID_PLAN_VERSION_NAME: "INVALID_PLAN_VERSION_NAME",
  INVALID_PLAN_VERSION_NUMBER: "INVALID_PLAN_VERSION_NUMBER",
  INVALID_PLAN_VERSION_STATE: "INVALID_PLAN_VERSION_STATE",
  INVALID_PLAN_VERSION_TEXT: "INVALID_PLAN_VERSION_TEXT",
  INVALID_PRIMARY_FACTORY_ID: "INVALID_PRIMARY_FACTORY_ID",
  INVALID_PRODUCTION_PLAN_TEXT: "INVALID_PRODUCTION_PLAN_TEXT",
  INVALID_QUANTITY_PRECISION: "INVALID_QUANTITY_PRECISION",
  INVALID_RESULT_VALIDITY: "INVALID_RESULT_VALIDITY",
  INVALID_ROUTING_DEFINITION: "INVALID_ROUTING_DEFINITION",
  INVALID_ROUTING_DIAGNOSIS: "INVALID_ROUTING_DIAGNOSIS",
  INVALID_ROUTING_OPERATION_ID: "INVALID_ROUTING_OPERATION_ID",
  INVALID_SCENARIO_ASSUMPTION_RELATION: "INVALID_SCENARIO_ASSUMPTION_RELATION",
  INVALID_SHIFT_ID: "INVALID_SHIFT_ID",
  INVALID_SHIFT_SEQUENCE: "INVALID_SHIFT_SEQUENCE",
  INVALID_SOURCE_REVISION: "INVALID_SOURCE_REVISION",
  INVALID_STANDARD_DURATION: "INVALID_STANDARD_DURATION",
  PRODUCTION_PLAN_ALREADY_ACTIVE: "PRODUCTION_PLAN_ALREADY_ACTIVE",
  PRODUCTION_PLAN_ALREADY_INACTIVE: "PRODUCTION_PLAN_ALREADY_INACTIVE",
  REPLACEMENT_VERSION_SELF_REFERENCE: "REPLACEMENT_VERSION_SELF_REFERENCE",
  INVALID_STALE_REASON_DETECTION: "INVALID_STALE_REASON_DETECTION",
  INVALID_RESULT_VALIDITY_EVALUATION: "INVALID_RESULT_VALIDITY_EVALUATION",
  INVALID_REVISION_IMPACT_MAP: "INVALID_REVISION_IMPACT_MAP",
  INVALID_CURRENT_DIAGNOSIS_SOURCE: "INVALID_CURRENT_DIAGNOSIS_SOURCE",
  INVALID_REPOSITORY: "INVALID_REPOSITORY",
  INVALID_REPOSITORY_STATE: "INVALID_REPOSITORY_STATE",
  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  DUPLICATE_UNIQUE_KEY: "DUPLICATE_UNIQUE_KEY",
  INVALID_DIAGNOSIS_EXECUTION_DATA: "INVALID_DIAGNOSIS_EXECUTION_DATA",
  INVALID_DIAGNOSIS_EXECUTION_DATA_PROVIDER:
    "INVALID_DIAGNOSIS_EXECUTION_DATA_PROVIDER",
  INVALID_RUN_PLAN_DIAGNOSIS: "INVALID_RUN_PLAN_DIAGNOSIS",
  DIAGNOSIS_EXECUTION_NOT_ALLOWED: "DIAGNOSIS_EXECUTION_NOT_ALLOWED",
  INVALID_REPOSITORY_SNAPSHOT: "INVALID_REPOSITORY_SNAPSHOT",
  INVALID_BACKUP_DOCUMENT: "INVALID_BACKUP_DOCUMENT",
  UNSUPPORTED_BACKUP_SCHEMA_VERSION: "UNSUPPORTED_BACKUP_SCHEMA_VERSION",
  PERSISTENCE_STORAGE_ERROR: "PERSISTENCE_STORAGE_ERROR",
  PERSISTENCE_RESTORE_FAILED: "PERSISTENCE_RESTORE_FAILED",
  INVALID_DIAGNOSIS_EXECUTION_DATA_SNAPSHOT:
    "INVALID_DIAGNOSIS_EXECUTION_DATA_SNAPSHOT",
  INVALID_DIAGNOSIS_EXECUTION_DATA_SNAPSHOT_SERVICE:
    "INVALID_DIAGNOSIS_EXECUTION_DATA_SNAPSHOT_SERVICE",
  INVALID_EXTERNAL_DATA_DOCUMENT: "INVALID_EXTERNAL_DATA_DOCUMENT",
  UNSUPPORTED_EXTERNAL_DATA_SCHEMA_VERSION:
    "UNSUPPORTED_EXTERNAL_DATA_SCHEMA_VERSION",
  DUPLICATE_DIAGNOSIS_EXECUTION_DATA:
    "DUPLICATE_DIAGNOSIS_EXECUTION_DATA",
  EXTERNAL_DATA_RESTORE_FAILED: "EXTERNAL_DATA_RESTORE_FAILED",
  EXTERNAL_DATA_IMPORT_STALE_PREVIEW:
    "EXTERNAL_DATA_IMPORT_STALE_PREVIEW",
  EXTERNAL_DATA_IMPORT_COMMIT_NOT_ALLOWED:
    "EXTERNAL_DATA_IMPORT_COMMIT_NOT_ALLOWED",
  INVALID_EXTERNAL_DATA_IMPORT_CONTROLLER:
    "INVALID_EXTERNAL_DATA_IMPORT_CONTROLLER",
  INVALID_EXTERNAL_DATA_EXPORT_SERVICE:
    "INVALID_EXTERNAL_DATA_EXPORT_SERVICE",
  EXTERNAL_DATA_EXPORT_FAILED: "EXTERNAL_DATA_EXPORT_FAILED",
  INVALID_EXTERNAL_DATA_CSV_BUNDLE:
    "INVALID_EXTERNAL_DATA_CSV_BUNDLE",
  INVALID_EXTERNAL_DATA_CSV_BUNDLE_BUILDER:
    "INVALID_EXTERNAL_DATA_CSV_BUNDLE_BUILDER",
  EXTERNAL_DATA_CSV_BUNDLE_VALIDATION_FAILED:
    "EXTERNAL_DATA_CSV_BUNDLE_VALIDATION_FAILED",
  INVALID_APPLICATION_SNAPSHOT_SERVICE:
    "INVALID_APPLICATION_SNAPSHOT_SERVICE",
  APPLICATION_SNAPSHOT_ROLLBACK_FAILED:
    "APPLICATION_SNAPSHOT_ROLLBACK_FAILED",
  INVALID_PERSISTENCE_COORDINATOR: "INVALID_PERSISTENCE_COORDINATOR",
  INVALID_BACKUP_CONTROLLER: "INVALID_BACKUP_CONTROLLER",
  INVALID_TRANSACTION_MANAGER: "INVALID_TRANSACTION_MANAGER",
  TRANSACTION_ALREADY_ACTIVE: "TRANSACTION_ALREADY_ACTIVE",
  TRANSACTION_ROLLBACK_FAILED: "TRANSACTION_ROLLBACK_FAILED",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR"
});

export class ApplicationError extends Error {
  constructor(
    code,
    message,
    {
      category = ERROR_CATEGORY.APPLICATION,
      details = {},
      cause = undefined
    } = {}
  ) {
    assertRegisteredErrorCode(code);
    assertErrorCategory(category);

    if (typeof message !== "string" || message.trim() === "") {
      throw new TypeError("ApplicationError message must be a non-empty string.");
    }

    super(message.trim(), cause === undefined ? undefined : { cause });

    this.name = "ApplicationError";
    this.code = code;
    this.category = category;
    this.details = Object.freeze({ ...assertPlainObject(
      details,
      ERROR_CODES.INVALID_PLAIN_OBJECT,
      "details"
    ) });
  }

  toJSON() {
    return {
      name: this.name,
      code: this.code,
      category: this.category,
      message: this.message,
      details: this.details
    };
  }
}

export function isApplicationError(error) {
  return error instanceof ApplicationError;
}

export function hasErrorCode(error, code) {
  return isApplicationError(error) && error.code === code;
}

export function assertRegisteredErrorCode(code) {
  if (!isCodeValue(ERROR_CODES, code)) {
    throw new TypeError(`Unknown error code: ${String(code)}`);
  }
  return code;
}

export function assertErrorCategory(category) {
  if (!isCodeValue(ERROR_CATEGORY, category)) {
    throw new TypeError(`Unknown error category: ${String(category)}`);
  }
  return category;
}


export function createApplicationError(code, message, details = {}, cause) {
  return new ApplicationError(code, message, {
    category: ERROR_CATEGORY.APPLICATION,
    details,
    cause
  });
}

export function createDomainError(code, message, details = {}, cause) {
  return new ApplicationError(code, message, {
    category: ERROR_CATEGORY.DOMAIN,
    details,
    cause
  });
}

export function createImportError(code, message, details = {}, cause) {
  return new ApplicationError(code, message, {
    category: ERROR_CATEGORY.IMPORT,
    details,
    cause
  });
}

export function createRepositoryError(code, message, details = {}, cause) {
  return new ApplicationError(code, message, {
    category: ERROR_CATEGORY.REPOSITORY,
    details,
    cause
  });
}

export function wrapUnexpectedError(error, details = {}) {
  if (isApplicationError(error)) {
    return error;
  }

  return new ApplicationError(
    ERROR_CODES.UNEXPECTED_ERROR,
    "An unexpected error occurred.",
    {
      category: ERROR_CATEGORY.UNEXPECTED,
      details,
      cause: error
    }
  );
}

export function assertNonEmptyString(
  value,
  code = ERROR_CODES.INVALID_NON_EMPTY_STRING,
  label = "value"
) {
  if (typeof value !== "string" || value.trim() === "") {
    throw createDomainError(
      code,
      `${label} must be a non-empty string.`,
      { value, label }
    );
  }

  return value.trim();
}

export function assertBoolean(
  value,
  code = ERROR_CODES.INVALID_BOOLEAN,
  label = "value"
) {
  if (typeof value !== "boolean") {
    throw createDomainError(
      code,
      `${label} must be boolean.`,
      { value, label }
    );
  }

  return value;
}

export function assertPositiveInteger(
  value,
  code = ERROR_CODES.INVALID_POSITIVE_INTEGER,
  label = "value"
) {
  if (!Number.isInteger(value) || value <= 0) {
    throw createDomainError(
      code,
      `${label} must be a positive integer.`,
      { value, label }
    );
  }

  return value;
}

export function assertNonNegativeInteger(
  value,
  code = ERROR_CODES.INVALID_NON_NEGATIVE_INTEGER,
  label = "value"
) {
  if (!Number.isInteger(value) || value < 0) {
    throw createDomainError(
      code,
      `${label} must be a non-negative integer.`,
      { value, label }
    );
  }

  return value;
}

export function assertFiniteNumber(
  value,
  code = ERROR_CODES.INVALID_FINITE_NUMBER,
  label = "value",
  { min = -Infinity, max = Infinity } = {}
) {
  if (!Number.isFinite(value) || value < min || value > max) {
    throw createDomainError(
      code,
      `${label} must be a finite number between ${min} and ${max}.`,
      { value, label, min, max }
    );
  }

  return value;
}

export function assertArray(
  value,
  code = ERROR_CODES.INVALID_ARRAY,
  label = "value"
) {
  if (!Array.isArray(value)) {
    throw createDomainError(
      code,
      `${label} must be an array.`,
      { value, label }
    );
  }

  return value;
}

export function assertPlainObject(
  value,
  code = ERROR_CODES.INVALID_PLAIN_OBJECT,
  label = "value"
) {
  const isPlainObject =
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    (Object.getPrototypeOf(value) === Object.prototype ||
      Object.getPrototypeOf(value) === null);

  if (!isPlainObject) {
    throw createDomainError(
      code,
      `${label} must be a plain object.`,
      { value, label }
    );
  }

  return value;
}

export function assertCodeValue(
  value,
  codeMap,
  code = ERROR_CODES.INVALID_CODE_VALUE,
  label = "value"
) {
  if (!isCodeValue(codeMap, value)) {
    throw createDomainError(
      code,
      `${label} must be one of: ${getCodeValues(codeMap).join(", ")}.`,
      {
        value,
        label,
        allowedValues: getCodeValues(codeMap)
      }
    );
  }

  return value;
}
