export const ENGINE_ANALYSIS_STATUS = Object.freeze({
  UNANALYZED: "UNANALYZED",
  ANALYZING: "ANALYZING",
  ANALYZED: "ANALYZED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  REANALYZABLE: "REANALYZABLE"
});

export const ENGINE_EVALUATION_TYPE = Object.freeze({
  CP: "CP",
  MATE: "MATE",
  UNKNOWN: "UNKNOWN"
});

export const ENGINE_EVALUATION_PERSPECTIVE = Object.freeze({
  SENTE: "SENTE",
  SIDE_TO_MOVE: "SIDE_TO_MOVE"
});

export const ENGINE_CANDIDATE_TYPE = Object.freeze({
  MAJOR_DROPOFF: "MAJOR_DROPOFF",
  REVIEW_CANDIDATE: "REVIEW_CANDIDATE",
  GOOD_MOVE_CANDIDATE: "GOOD_MOVE_CANDIDATE"
});

export const ENGINE_ANALYSIS_SCHEMA_VERSION = 1;
