import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root=path.dirname(fileURLToPath(import.meta.url));
const baseline=JSON.parse(fs.readFileSync(path.join(root,"SOURCE_OF_TRUTH_V1_6_BASELINE_HASHES.json"),"utf8"));
const output=path.join(root,"STATIC_VERIFICATION_RESULT.txt");
const syntaxOutput=path.join(root,"SYNTAX_CHECK_RESULT.txt");
const norm=v=>v.split(path.sep).join("/");
const hash=f=>crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex");
const read=f=>fs.readFileSync(path.join(root,f),"utf8");
const exists=f=>fs.existsSync(path.join(root,f));
function list(dir=root){let a=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if([".git","node_modules","__pycache__"].includes(e.name))continue;if(e.name==="browser-verification-backup.json")continue;const full=path.join(dir,e.name);a.push(...(e.isDirectory()?list(full):[norm(path.relative(root,full))]));}return a.sort();}
const pass=[],fail=[];const check=(n,c,d="")=>(c?pass:fail).push(`${c?"PASS":"FAIL"} | ${n}${d?` | ${d}`:""}`);
const files=list(), baseFiles=Object.keys(baseline.files).sort(), set=new Set(files);
const deleted=baseFiles.filter(f=>!set.has(f));
const shared=baseFiles.filter(f=>set.has(f));
const modified=shared.filter(f=>hash(path.join(root,f))!==baseline.files[f]);
const unchanged=shared.filter(f=>hash(path.join(root,f))===baseline.files[f]);
const added=files.filter(f=>!(f in baseline.files));
check("Ver.1.6 Source of Truth file count",baseline.fileCount===296&&baseFiles.length===296,`${baseline.fileCount}/${baseFiles.length}`);
check("No Ver.1.6 files deleted",deleted.length===0,deleted.join(", "));
check("LICENSE hash preserved",baseline.files["LICENSE"]===hash(path.join(root,"LICENSE")));
const js=files.filter(f=>/\.(?:js|mjs)$/.test(f)), syntax=[];
for(const f of js){try{execFileSync(process.execPath,["--check",path.join(root,f)],{stdio:"pipe"});syntax.push(`PASS | ${f}`)}catch(e){syntax.push(`FAIL | ${f} | ${e.stderr?.toString().trim()??e.message}`)}}
fs.writeFileSync(syntaxOutput,["Shogi Reflection Ver.1.7 Syntax Check","Date: 2026-08-09",`Files: ${js.length}`,"",...syntax,""].join("\n"));
check("All JavaScript syntax",syntax.every(x=>x.startsWith("PASS")),String(js.length));
const missing=[];for(const f of js){for(const m of read(f).matchAll(/(?:from\s+|import\s*\()(["'])(\.\.?\/[^"']+)\1/g)){const target=path.resolve(path.dirname(path.join(root,f)),m[2]);if(!fs.existsSync(target))missing.push(`${f} -> ${m[2]}`)}}
check("Missing Import = 0",missing.length===0,missing.join(", "));
const required=["AnalyzeGame.js","ShogiEnginePort.js","YaneuraOuEngineAdapter.js","UsiEngineAdapter.js","EvaluationNormalizer.js","EngineCandidateSelector.js","EngineAnalysisRepository.js","BrowserEngineAnalysisView.js","Ver.1.7操作手順書.md","ENGINE_INTEGRATION_DESIGN.md","ENGINE_CANDIDATE_SELECTION_DESIGN.md","ENGINE_LICENSE_AUDIT.md","SOURCE_OF_TRUTH_AUDIT.md","COMPLETION_REPORT.md","VISUAL_VERIFICATION_RESULT.txt","PERFORMANCE_RESULT.txt","EngineUiFlowV17.test.js","CandidateReplayV17.test.js","CandidateKeyPositionV17.test.js","PieceGraphicsV17.test.js","LICENSE"];
for(const f of required)check(`Required file: ${f}`,exists(f));
const pkg=JSON.parse(read("package.json"));check("package version",pkg.version==="1.7.0",pkg.version);check("test script",pkg.scripts?.test==="node --test");check("check script",pkg.scripts?.check==="node verify.mjs");
const html=read("index.html"),css=read("style.css"),piece=read("ShogiPieceSvg.js"),main=read("main.js"),form=read("BrowserGameReviewFormView.js"),review=read("GameReview.js"),rules=read("Design Rules.md"),engineView=read("BrowserEngineAnalysisView.js");
check("Seven Step panels",(html.match(/data-step-panel=/g)??[]).length===7);
const step3=html.match(/data-step-panel="3"[\s\S]*?data-step-panel="4"/)?.[0]??""; const step4=html.match(/data-step-panel="4"[\s\S]*?data-step-panel="5"/)?.[0]??"";
check("Engine UI in STEP3",step3.includes('id="engine-analysis-panel"')&&step3.includes('id="analyze-game"'));
check("Engine UI not centered in STEP4",!step4.includes('id="engine-analysis-panel"'));
check("Manual KeyPosition retained",html.includes('id="add-current-position"')&&html.includes('id="add-key-position"'));
check("FACT examples presentation only",form.includes('placeholder="例：相手の飛車が自陣へ侵入')&&!form.includes('value="例：相手の飛車が自陣へ侵入'));
check("Fixed 9x9 geometry retained",/grid-template-columns\s*:\s*repeat\(9,\s*minmax\(0,\s*1fr\)\)/.test(css)&&/grid-template-rows\s*:\s*repeat\(9,\s*minmax\(0,\s*1fr\)\)/.test(css));
check("Original polished SVG",piece.includes('M50 5 C52 5 53.5 5.6 55.1 6.6')&&piece.includes('piece-face-highlight'));
check("Promoted stacked labels",piece.includes('piece-label-stacked')&&piece.includes('<tspan x="50" y="48">'));
check("No bundled webfont declaration",!css.includes('@font-face'));
check("No external piece image URL",!piece.match(/https?:\/\//));
check("ReplayScrollPolicy hash preserved",baseline.files["ReplayScrollPolicy.js"]===hash(path.join(root,"ReplayScrollPolicy.js")));
check("GameReview Domain hash preserved",baseline.files["GameReview.js"]===hash(path.join(root,"GameReview.js")));
check("GameReview storage hash preserved",baseline.files["GameReviewSnapshotService.js"]===hash(path.join(root,"GameReviewSnapshotService.js")));
check("Game backup schemaVersion remains 1",read("GameReviewSnapshotService.js").includes("SHOGI_REFLECTION_SCHEMA_VERSION = 1"));
check("3-5 KeyPosition rule retained",review.includes("keyPositions.length > 5")&&review.includes("this.keyPositions.length >= 3"));
check("Engine Port isolated from USI",!/\b(position sfen|setoption|bestmove|score cp|score mate)\b/.test(read("AnalyzeGame.js")));
check("USI protocol stays Adapter",read("UsiEngineAdapter.js").includes("position sfen")&&read("UsiEngineAdapter.js").includes("bestmove"));
check("Re-analysis history retained",read("EngineAnalysisRepository.js").includes("[...history, result]"));
check("Separate Engine storage key",read("LocalStorageEngineAnalysisStore.js").includes("engine-analyses.v1"));
check("Candidate does not auto-register",(html.includes("Engineは重要局面を自動確定しません")||html.includes("自動登録はしません"))&&main.includes("data-engine-add-key-position"));
const cjump=main.match(/data-engine-replay-ply[\s\S]*?\n\s*}\);/)?.[0]??"";check("Candidate Jump uses existing Replay",cjump.includes("replayController.jump")&&!/scrollIntoView|navigateToStep/.test(cjump));
const mljump=main.match(/replay-move-list[\s\S]*?\n}\);/)?.[0]??"";check("Move List Jump no page scroll",mljump.includes("replayController.jump")&&!/scrollIntoView|window\.scroll/.test(mljump));
check("STEP3 displays primary candidates only",engineView.includes("primary.map(candidateMarkup)")&&!engineView.includes("otherCandidates.slice"));
check("Saved Viewer has separate analysis status",read("BrowserGameReviewLibraryView.js").includes("analysisStatus"));
check("Design Rules Ver1.7",rules.includes("INTERLUDE-Rule-FA")&&rules.includes("INTERLUDE-Rule-FG"));
const tr=exists("TEST_RESULT.txt")?read("TEST_RESULT.txt"):"";check("Automated tests failed zero",/Failed:\s*0/.test(tr));
const br=exists("BROWSER_VERIFICATION_RESULT.txt")?read("BROWSER_VERIFICATION_RESULT.txt"):"";check("Browser verification failed zero",/Failed:\s*0/.test(br));check("Browser 3-5 candidate recorded",br.includes("Long game Candidate 3-5"));
const vr=exists("VISUAL_VERIFICATION_RESULT.txt")?read("VISUAL_VERIFICATION_RESULT.txt"):"";check("Visual verification failed zero",/Failed:\s*0/.test(vr));
const report=["Shogi Reflection Ver.1.7 Static Verification","Date: 2026-08-09","",`Files: ${files.length}`,`Ver.1.6 baseline files: ${baseFiles.length}`,`Hash-identical Ver.1.6 files: ${unchanged.length}`,`Modified Ver.1.6 files: ${modified.length}`,`Added Ver.1.7 files: ${added.length}`,`Deleted Ver.1.6 files: ${deleted.length}`,`Syntax checked: ${js.length}`,`Missing imports: ${missing.length}`,`Passed checks: ${pass.length}`,`Failed checks: ${fail.length}`,"","Modified Ver.1.6 files:",...modified.map(x=>`- ${x}`),"","Added Ver.1.7 files:",...added.map(x=>`- ${x}`),"","Deleted Ver.1.6 files:",...(deleted.length?deleted.map(x=>`- ${x}`):["- none"]),"",...pass,...fail,""].join("\n");
fs.writeFileSync(output,report);console.log(report.split("\n").slice(0,13).join("\n"));if(fail.length)process.exit(1);
