export const PERSISTENCE_ERROR_CODES = Object.freeze({
  INVALID_SNAPSHOT_DOCUMENT: "INVALID_SNAPSHOT_DOCUMENT",
  INVALID_SNAPSHOT_JSON: "INVALID_SNAPSHOT_JSON",
  INVALID_APPLICATION_ID: "INVALID_APPLICATION_ID",
  UNSUPPORTED_SCHEMA_VERSION: "UNSUPPORTED_SCHEMA_VERSION",
  INVALID_EXPORTED_AT: "INVALID_EXPORTED_AT",
  INVALID_REPOSITORY_REVISION: "INVALID_REPOSITORY_REVISION",
  DUPLICATE_GAME_REVIEW_ID: "DUPLICATE_GAME_REVIEW_ID",
  DUPLICATE_KEY_POSITION_ID: "DUPLICATE_KEY_POSITION_ID",
  DOMAIN_RULE_VIOLATION: "DOMAIN_RULE_VIOLATION",
  SNAPSHOT_RESTORE_FAILED: "SNAPSHOT_RESTORE_FAILED",
  LOCAL_STORAGE_UNAVAILABLE: "LOCAL_STORAGE_UNAVAILABLE",
  LOCAL_STORAGE_SAVE_FAILED: "LOCAL_STORAGE_SAVE_FAILED",
  LOCAL_STORAGE_LOAD_FAILED: "LOCAL_STORAGE_LOAD_FAILED",
  LOCAL_STORAGE_DELETE_FAILED: "LOCAL_STORAGE_DELETE_FAILED",
  INVALID_BACKUP_JSON: "INVALID_BACKUP_JSON"
});

export class PersistenceError extends Error {
  constructor(code, message, context = {}, options = {}) {
    super(message, options);
    this.name = "PersistenceError";
    this.code = code;
    this.context = Object.freeze({ ...context });
  }
}
