export const CAPACITY_EVENT_TYPES = Object.freeze({
  WORKER_BECAME_AVAILABLE: "WORKER_BECAME_AVAILABLE",
  WORKER_BECAME_UNAVAILABLE: "WORKER_BECAME_UNAVAILABLE",
  CAPACITY_CHANGED: "CAPACITY_CHANGED",
  SHIFT_STARTED: "SHIFT_STARTED",
  SHIFT_ENDED: "SHIFT_ENDED",
  EQUIPMENT_CAPACITY_CHANGED: "EQUIPMENT_CAPACITY_CHANGED",
  FACTORY_CAPACITY_CHANGED: "FACTORY_CAPACITY_CHANGED"
});
