export const WORKER_CAPACITY_STATES = Object.freeze({
  UNAVAILABLE: "UNAVAILABLE",
  AVAILABLE_UNASSIGNED: "AVAILABLE_UNASSIGNED",
  AVAILABLE_NOT_SELECTED: "AVAILABLE_NOT_SELECTED",
  CONTRIBUTING: "CONTRIBUTING"
});

export const EQUIPMENT_CAPACITY_STATES = Object.freeze({
  AVAILABLE: "AVAILABLE",
  BLOCKED: "BLOCKED"
});

export const FACTORY_CAPACITY_STATES = Object.freeze({
  FULL: "FULL",
  PARTIAL: "PARTIAL",
  NONE: "NONE"
});

export const CAPACITY_REASON_CODES = Object.freeze({
  WORKER_WITHIN_SHIFT: "WORKER_WITHIN_SHIFT",
  WORKER_OUTSIDE_SHIFT: "WORKER_OUTSIDE_SHIFT",
  WORKER_ABSENT: "WORKER_ABSENT",
  WORKER_NOT_ASSIGNED: "WORKER_NOT_ASSIGNED",
  WORKER_AVAILABLE_NOT_SELECTED: "WORKER_AVAILABLE_NOT_SELECTED",
  WORKER_CONTRIBUTING: "WORKER_CONTRIBUTING",
  EQUIPMENT_CAPACITY_AVAILABLE: "EQUIPMENT_CAPACITY_AVAILABLE",
  EQUIPMENT_CAPACITY_BLOCKED: "EQUIPMENT_CAPACITY_BLOCKED",
  FACTORY_FULL_CAPACITY: "FACTORY_FULL_CAPACITY",
  FACTORY_PARTIAL_CAPACITY: "FACTORY_PARTIAL_CAPACITY",
  FACTORY_NO_CAPACITY: "FACTORY_NO_CAPACITY"
});
