export const CAPACITY_UNITS = Object.freeze({
  PIECE: "PIECE",
  KILOGRAM: "KILOGRAM",
  LOT: "LOT"
});

export const CAPACITY_BASES = Object.freeze({
  HOUR: "HOUR",
  SHIFT: "SHIFT",
  DAY: "DAY"
});

export const FACTORY_DAY_TYPES = Object.freeze({
  OPERATING: "OPERATING",
  FACTORY_HOLIDAY: "FACTORY_HOLIDAY",
  COMPANY_HOLIDAY: "COMPANY_HOLIDAY",
  EXTRA_OPERATING: "EXTRA_OPERATING",
  PLANNED_STOP: "PLANNED_STOP"
});

export const EQUIPMENT_CALENDAR_STATES = Object.freeze({
  AVAILABLE: "AVAILABLE",
  PERIODIC_INSPECTION: "PERIODIC_INSPECTION",
  BREAKDOWN: "BREAKDOWN",
  REPAIR: "REPAIR",
  PLANNED_STOP: "PLANNED_STOP",
  DEGRADED: "DEGRADED"
});

export const WORKER_CALENDAR_STATES = Object.freeze({
  PRESENT: "PRESENT",
  ABSENT: "ABSENT",
  PAID_LEAVE: "PAID_LEAVE",
  LEAVE: "LEAVE",
  LATE: "LATE",
  EARLY_LEAVE: "EARLY_LEAVE",
  OVERTIME: "OVERTIME",
  PARTIAL: "PARTIAL",
  SUPPORT_OUT: "SUPPORT_OUT",
  SUPPORT_IN: "SUPPORT_IN"
});

export const SHIFT_CAPACITY_STATES = Object.freeze({
  RUNNING: "RUNNING",
  PARTIAL: "PARTIAL",
  BLOCKED: "BLOCKED"
});

export const REASON_CODES = Object.freeze({
  OPERABLE: "OPERABLE",
  PARTIAL_OPERATION: "PARTIAL_OPERATION",
  FACTORY_HOLIDAY: "FACTORY_HOLIDAY",
  SHIFT_NOT_PLANNED: "SHIFT_NOT_PLANNED",
  EQUIPMENT_STOPPED: "EQUIPMENT_STOPPED",
  EQUIPMENT_NOT_USABLE: "EQUIPMENT_NOT_USABLE",
  MISSING_REQUIRED_SKILL_SETTING: "MISSING_REQUIRED_SKILL_SETTING",
  MISSING_CAPACITY_RULE: "MISSING_CAPACITY_RULE",
  WORKER_COUNT_SHORTAGE: "WORKER_COUNT_SHORTAGE",
  SKILL_SHORTAGE: "SKILL_SHORTAGE",
  ASSIGNMENT_CONFLICT: "ASSIGNMENT_CONFLICT",
  UNASSIGNED: "UNASSIGNED",
  OUTSIDE_WORKING_TIME: "OUTSIDE_WORKING_TIME",
  SKILL_EXPIRED: "SKILL_EXPIRED",
  CROSS_FACTORY_ASSIGNMENT: "CROSS_FACTORY_ASSIGNMENT",
  CAPACITY_CONSUMED: "CAPACITY_CONSUMED",
  OVERLOAD: "OVERLOAD",
  ROUTING_MISSING: "ROUTING_MISSING",
  INVALID_INPUT: "INVALID_INPUT"
});

export const VALID_CAPACITY_UNITS = Object.freeze(Object.values(CAPACITY_UNITS));
export const VALID_CAPACITY_BASES = Object.freeze(Object.values(CAPACITY_BASES));
