export const FACTORY_ALLOCATION_REASON_CODES = Object.freeze({
  EQUIPMENT_NOT_OPERABLE: "EQUIPMENT_NOT_OPERABLE",
  MATERIAL_NOT_AVAILABLE: "MATERIAL_NOT_AVAILABLE",
  WORKER_COUNT_SHORTAGE: "WORKER_COUNT_SHORTAGE",
  SKILL_REQUIREMENT_SHORTAGE: "SKILL_REQUIREMENT_SHORTAGE",
  WORKER_RESERVED_BY_OTHER_EQUIPMENT:
    "WORKER_RESERVED_BY_OTHER_EQUIPMENT",
  NO_GLOBAL_MATCHING: "NO_GLOBAL_MATCHING",
  HIGHER_PRIORITY_EQUIPMENT_SELECTED:
    "HIGHER_PRIORITY_EQUIPMENT_SELECTED",
  STABLE_TIE_BREAK_APPLIED: "STABLE_TIE_BREAK_APPLIED",
  ALLOCATION_COMPLETE: "ALLOCATION_COMPLETE"
});

export const EQUIPMENT_EXECUTION_STATES = Object.freeze({
  RUNNING: "RUNNING",
  BLOCKED: "BLOCKED"
});
