import { registerDay29MasterTests } from "./day29Master.test.js";
import { registerDay29AssignmentTests } from "./day29Assignment.test.js";
import { registerDay29CapacityTests } from "./day29Capacity.test.js";
import { registerDay29SimulationTests } from "./day29Simulation.test.js";
import { registerDay29RepositoryImportTests } from "./day29RepositoryImport.test.js";
import { registerDay29ValidationTests } from "./day29Validation.test.js";
import { registerDay28RepositoryTests } from "./day28Repository.test.js";
import { registerTimeSlotTests } from "./timeSlot.test.js";
import { registerTemporalAvailabilityTests } from "./temporalAvailability.test.js";
import { registerCapacityDomainTests } from "./capacityDomain.test.js";
import { registerCapacityCalendarApplicationTests } from "./capacityCalendarApplication.test.js";
import { registerCapacityEventTests } from "./capacityEvent.test.js";
import { registerRequiredSkillRequirementTests } from "./requiredSkillRequirement.test.js";
import { registerRequiredSkillCompositionTests } from "./requiredSkillComposition.test.js";
import { registerEquipmentTests } from "./equipment.test.js";
import { registerWorkerRoleMatchingTests } from "./workerRoleMatching.test.js";
import { registerSkillRequirementTests } from "./skillRequirement.test.js";
import { registerEquipmentAvailabilityTests } from "./equipmentAvailability.test.js";
import { registerReplayFactoryStateTests } from "./replayFactoryState.test.js";
import { registerDay23RegressionTests } from "./day23Regression.test.js";
import { registerDay24RegressionTests } from "./day24Regression.test.js";
import { registerDay25RegressionTests } from "./day25Regression.test.js";
import { registerDay26RegressionTests } from "./day26Regression.test.js";
import { registerLocalStorageRepositoryTests } from "./localStorageRepository.test.js";
import { registerAssignmentStateTests } from "./factoryAllocationAssignment.test.js";
import { registerRoleSlotMatchingTests } from "./roleSlotMatching.test.js";
import { registerFactoryAllocationTests } from "./factoryAllocation.test.js";
import { registerFactoryAllocationPriorityTests } from "./factoryAllocationPriority.test.js";
import { registerFactoryAllocationReasonTests } from "./factoryAllocationReason.test.js";
import { registerFactoryAllocationEventReplayTests } from "./factoryAllocationEventReplay.test.js";
import { registerFactoryAllocationResultTests } from "./factoryAllocationResult.test.js";
import { registerFactoryAllocationApplicationTests } from "./factoryAllocationApplication.test.js";

export function registerCoreTests() {
  registerRequiredSkillRequirementTests();
  registerRequiredSkillCompositionTests();
  registerEquipmentTests();
  registerWorkerRoleMatchingTests();
  registerSkillRequirementTests();
  registerEquipmentAvailabilityTests();
  registerReplayFactoryStateTests();
  registerDay23RegressionTests();
  registerDay24RegressionTests();
  registerDay25RegressionTests();
  registerDay26RegressionTests();
  registerLocalStorageRepositoryTests();
  registerAssignmentStateTests();
  registerRoleSlotMatchingTests();
  registerFactoryAllocationTests();
  registerFactoryAllocationPriorityTests();
  registerFactoryAllocationReasonTests();
  registerFactoryAllocationEventReplayTests();
  registerFactoryAllocationResultTests();
  registerFactoryAllocationApplicationTests();
  registerTimeSlotTests();
  registerTemporalAvailabilityTests();
  registerCapacityDomainTests();
  registerCapacityCalendarApplicationTests();
  registerCapacityEventTests();
  registerDay28RepositoryTests();
  registerDay29MasterTests();
  registerDay29AssignmentTests();
  registerDay29CapacityTests();
  registerDay29SimulationTests();
  registerDay29RepositoryImportTests();
  registerDay29ValidationTests();
}
